# Generated by Django 4.2 on 2025-04-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooluser',
            options={'managed': False},
        ),
    ]
