# Generated by Django 5.2 on 2025-04-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0003_user_info_classinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='classinfo',
            name='class_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='create_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
