# Generated by Django 5.2 on 2025-04-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0004_remove_classinfo_id_classinfo_class_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooluser',
            options={},
        ),
    ]
