# Generated by Django 5.2 on 2025-04-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0005_alter_schooluser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='create_grade',
            field=models.CharField(default='NULL', max_length=10),
            preserve_default=False,
        ),
    ]
